spring:
  application:
    name: ShulkerSync

  datasource:
    url: jdbc:sqlite:shulker.db
    driver-class-name: org.sqlite.JDBC

    # 实际上 username、password字段无意义，SQLITE无用户权限管理
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xyz.saturnhalo.domain.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true